### ISSUE TITLE
Do away with the need for project

### ISSUE THREAD

**Issue by PhilETaylor** [zergin/sublime-hashids#1]
Hi there

Just asking how much work would it be to NOT have the hash bound to a project - but to have the seed hash prompted for when invoked encode/decode? 

I use sublime as more of a quick text editor and not my IDE (Which is @phpstorm) and so my main use for this package would be to convert manually (encode/decode) 

My workflow being - new document -> paste in encoded hash -> invoke pallet menu -> select hashids: decode -> enter the seed -> highlighted encoded string now converted back into a integer/array

Would this be easy to implement?

**Comment by zergin** [comment]
Not exactly what you asked for but plugin now supportts inline passing of salt:

```
salt=abc;ids=1,2,3 => G7CYSG
salt=abc;1,2,3 => G7CYSG
```

```
salt=abc;hash=G7CYSG => 1,2,3
salt=abc;G7CYSG => 1,2,3
```

In such case project configuration is not required.
